### ISSUE TITLE
(not an issue) Will you update the mod to Neoforge? 

### ISSUE THREAD

**Issue by Unrectified** [Dev0Louis/Transfer#1]
Hi Louis.

Thank you very much for this little mod. It's so simple but really nice to be able to use the new transfert feature with only one command.

Just a little question, do you plan to update your to neoforge?

Thank you again and good luck :)

**Comment by Dev0Louis** [comment]
Hello Hantale,

I never developed for Neoforge, but as this is mod is not that complicated I will try it later this day.

Thank you for reaching out. :D

**Comment by Dev0Louis** [comment]
Oh wait Neo Forge does not have snapshot version, does it?

**Comment by Unrectified** [comment]
Well, neoforge vane not versions for snapsot but anyway it will be useless know. 
Thank you again for this little mod,
Have luck!
